# Generated by Django 4.0.3 on 2022-03-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_of_product',
            new_name='num_of_products',
        ),
    ]
