# Generated by Django 4.0.3 on 2022-03-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0002_rename_num_of_product_product_num_of_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AccountID', models.CharField(max_length=50, unique=True)),
                ('Area', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('MultipleLines', models.CharField(max_length=10)),
                ('InternetService', models.CharField(max_length=20)),
                ('PhoneService', models.CharField(max_length=10)),
                ('StreamingTV', models.CharField(max_length=10)),
                ('StreamingMovies', models.CharField(max_length=10)),
                ('TechSupport', models.CharField(max_length=10)),
                ('FaultPowerOutagePerMonth', models.IntegerField()),
                ('FaultCableCutPerMonth', models.IntegerField()),
                ('Contract', models.CharField(max_length=20)),
                ('PaperlessBilling', models.CharField(max_length=10)),
                ('PaymentMethod', models.CharField(max_length=20)),
                ('MonthlyCharges', models.FloatField()),
                ('TotalCharges', models.FloatField()),
                ('Churn', models.CharField(max_length=10)),
            ],
        ),
    ]
